# Generated by Django 2.0.6 on 2019-06-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photogallery', '0004_auto_20180607_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='ArchitecturalStyle',
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
